#!/bin/sh

function usage()
{
    CMDNAME=`basename $1`
    echo -e "[usage] ${CMDNAME} [IP address]" 1>&2
    exit
}

IPADDR=""
if [ $# -ge 1 ]; then
    IPADDR=$1
else
    read IPADDR
fi

t=`echo "${IPADDR}." | egrep '^([0-9]{1,3}\.){4}$' | wc -c`
if [ $t -eq 0 ]; then
    usage $0
    exit
fi

HOST=`nslookup ${IPADDR} | egrep 'name = (.+)$' | sed -E 's/	/ /g' | cut -d ' ' -f 4 | sed -E 's/\.$//g'`

if [ `echo -n "${HOST}" | wc -c` -le 1 ]; then
    echo -e "Cannot find hostname" 1>&2
    exit
fi

echo ${HOST}

