#!/bin/bash

function usage()
{
    CMDNAME=`basename $1`
    echo -e "[usage] ${CMDNAME} [IP address]" 1>&2
    exit
}

IPADDR=""

if [ $# -ge 1 ]; then
    IPADDR=$1
else
    read IPADDR
fi

t=`echo "${IPADDR}." | egrep '^([0-9]{1,3}\.){4}$' | wc -c`
if [ $t -eq 0 ]; then
    usage $0
    exit
fi

MAC=`ip n | egrep ${IPADDR} | sed -E 's/\t/ /g' | sed -E 's/ ( +)/ /g' | cut -d ' ' -f 5`
if [ `echo -n "${MAC}" | wc -c` -le 1 ]; then
    echo -e "MAC address is not found." 1>&2
    exit
fi

echo ${MAC}

